;!to "build/map.prg",cbm
; Generated by CharPad 2. Assemble with 64TASS or similar.


; General constants:-

TRUE = 1
FALSE = 0
COLRMETH_GLOBAL = 0
COLRMETH_PERTILE = 1
COLRMETH_PERCHAR = 2


; Project constants:-

COLOURING_METHOD = COLRMETH_PERCHAR
CHAR_MULTICOLOUR_MODE = TRUE
COLR_SCREEN = 0
COLR_CHAR_DEF = 11
COLR_CHAR_MC1 = 14
COLR_CHAR_MC2 = 6
CHAR_COUNT = 57
TILE_COUNT = 14
TILE_WID = 4
TILE_HEI = 4
MAP_WID = 10
MAP_HEI = 5
MAP_WID_CHRS = 40
MAP_HEI_CHRS = 20
MAP_WID_PXLS = 320
MAP_HEI_PXLS = 160


; Data block size constants:-

SZ_CHARSET_DATA        = 456
SZ_CHARSET_ATTRIB_DATA = 57
SZ_TILESET_DATA        = 224
SZ_MAP_DATA            = 50


; Data block address constants (dummy values):-

; ADDR_CHARSET_DATA        = $2000   ; nb. label = 'charset_data'        (block size = $1c8).
; ADDR_CHARSET_ATTRIB_DATA = $3900   ; nb. label = 'charset_attrib_data' (block size = $39).
ADDR_TILESET_DATA        = $2000   ; nb. label = 'tileset_data'        (block size = $e0).
; ADDR_MAP_DATA            = $3800   ; nb. label = 'map_data'            (block size = $32).





; CHAR SET ATTRIBUTE DATA : 57 attributes : total size is 57 ($39) bytes.
; nb. Upper nybbles = Material, Lower nybbles = Colour.

ADDR_CHARSET_ATTRIB_DATA
!byte $0b,$08,$08,$09,$00,$09,$09,$08,$08,$0b
!byte $08,$08,$08,$0d,$0d,$0d,$0d,$0d,$0d,$0d
!byte $0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d
!byte $0b,$0b,$09,$09,$09,$09,$09,$09,$09,$09
!byte $09,$09,$09,$09,$09,$09,$09,$09,$09,$09
!byte $1b,$fb,$fb,$fb,$fb,$fb,$f9



; MAP DATA : 1 (10x5) map : total size is 50 ($32) bytes.
; D70F
ADDR_MAP_DATA
!byte $0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d
!byte $04,$04,$00,$01,$02,$01,$02,$03,$04,$04
!byte $04,$04,$05,$06,$06,$06,$07,$08,$04,$04
!byte $04,$04,$04,$04,$04,$04,$04,$04,$0c,$04
!byte $0a,$0a,$0a,$0a,$0a,$0a,$0a,$0a,$0b,$09

; CHAR SET DATA : 57 (8 byte) chars : total size is 456 ($1c8) bytes.

ADDR_CHARSET_DATA
!byte $aa,$95,$90,$90,$90,$90,$90,$90,$aa,$55,$00,$00,$00,$00,$00,$00
!byte $90,$90,$90,$90,$90,$90,$90,$90,$00,$00,$00,$0c,$00,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$00,$00,$aa,$55,$00,$00,$00,$00,$00,$00
!byte $00,$00,$00,$0c,$3f,$0c,$00,$00,$aa,$56,$06,$06,$06,$06,$06,$06
!byte $06,$06,$06,$06,$06,$06,$06,$06,$ff,$55,$55,$55,$55,$55,$55,$55
!byte $00,$00,$00,$0c,$00,$00,$00,$00,$90,$90,$90,$90,$90,$90,$95,$aa
!byte $00,$00,$00,$00,$00,$00,$55,$aa,$00,$03,$0f,$0f,$3f,$3f,$ff,$ff
!byte $03,$03,$0f,$0f,$0f,$3f,$55,$aa,$ff,$f0,$f3,$f0,$ff,$ff,$55,$aa
!byte $00,$00,$00,$00,$00,$00,$00,$0f,$06,$06,$06,$06,$06,$06,$06,$f6
!byte $00,$00,$00,$00,$03,$0f,$30,$cf,$00,$03,$3c,$ff,$3f,$ff,$f3,$f3
!byte $3f,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$f6,$f6,$f6,$36,$c6,$c6,$f6,$f6
!byte $33,$cf,$cc,$c3,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
!byte $ff,$cf,$c3,$f3,$c3,$cf,$ff,$ff,$f6,$f6,$f6,$f6,$f6,$f6,$f6,$f6
!byte $fc,$c0,$3f,$ff,$ff,$ff,$55,$aa,$3f,$ff,$ff,$ff,$ff,$ff,$55,$aa
!byte $ff,$ff,$ff,$cf,$ff,$ff,$55,$aa,$f6,$f6,$f6,$f6,$f6,$f6,$56,$aa
!byte $c0,$70,$5c,$57,$55,$55,$55,$55,$00,$00,$00,$00,$c0,$70,$5c,$57
!byte $00,$03,$0f,$3f,$3f,$3f,$3f,$3f,$3f,$3f,$3d,$35,$16,$1a,$1b,$1a
!byte $fc,$fc,$7c,$5c,$94,$a4,$a4,$a4,$00,$c0,$f0,$fc,$fc,$fc,$fc,$fc
!byte $3f,$3f,$3f,$3f,$3f,$3f,$3f,$3f,$1a,$1a,$16,$35,$3d,$3f,$3d,$3b
!byte $e4,$a4,$94,$5c,$7c,$fc,$7c,$ec,$fc,$fc,$fc,$fc,$fc,$fc,$fc,$fc
!byte $3f,$3f,$3f,$3f,$33,$44,$55,$55,$3d,$3f,$3f,$3f,$0f,$53,$54,$55
!byte $7c,$fc,$fc,$fc,$f0,$c5,$15,$55,$fc,$fc,$fc,$fc,$cc,$11,$55,$55
!byte $54,$53,$53,$53,$53,$51,$51,$45,$15,$c5,$c5,$c5,$c5,$85,$85,$a1
!byte $45,$46,$46,$46,$4a,$46,$48,$42,$a1,$a1,$a1,$a1,$a1,$a1,$21,$81
!byte $3a,$3a,$3a,$3a,$3e,$3f,$3f,$3f,$82,$ac,$ac,$bc,$bc,$fc,$fc,$fc
!byte $f6,$d6,$56,$56,$56,$56,$56,$a8,$ff,$55,$55,$55,$55,$55,$55,$ff
!byte $ff,$57,$57,$57,$57,$57,$57,$ff,$ff,$57,$5d,$77,$5d,$57,$55,$ff
!byte $ff,$77,$dd,$77,$dd,$77,$55,$ff,$ff,$75,$dd,$77,$dd,$75,$55,$ff
!byte $55,$55,$55,$99,$66,$99,$66,$99

; TILE SET DATA : 14 (4x4) tiles : total size is 224 ($e0) bytes.

* = ADDR_TILESET_DATA
!byte $00,$01,$01,$01,$02,$03,$04,$04,$02,$04,$04,$03,$02,$04,$04,$04
!byte $01,$01,$01,$05,$04,$03,$04,$04,$04,$04,$04,$04,$06,$04,$04,$03
!byte $01,$01,$01,$01,$04,$04,$04,$06,$04,$03,$04,$04,$04,$04,$04,$04
!byte $01,$01,$01,$07,$04,$04,$03,$08,$03,$04,$04,$08,$04,$04,$03,$08
!byte $32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32
!byte $02,$04,$03,$04,$02,$04,$04,$0a,$02,$03,$04,$04,$0b,$0c,$0c,$0c
!byte $04,$04,$04,$04,$04,$04,$03,$04,$04,$03,$04,$04,$0c,$0c,$0c,$0c
!byte $04,$06,$04,$03,$04,$04,$04,$04,$0a,$04,$04,$0d,$0c,$0c,$0e,$0f
!byte $04,$04,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$1a,$1b,$1c,$1d
!byte $04,$04,$04,$04,$04,$04,$04,$04,$09,$09,$1e,$1f,$33,$33,$33,$34
!byte $04,$04,$04,$04,$04,$04,$04,$04,$09,$09,$09,$09,$33,$33,$33,$33
!byte $20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$2a,$2b,$35,$36,$36,$37
!byte $32,$32,$32,$32,$32,$2c,$2d,$32,$32,$2e,$2f,$32,$32,$30,$31,$32
!byte $38,$38,$38,$38,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32,$32


