;============================================================
; KERNAL Routines Locations
;============================================================

KRNL_CHKIN = $FFC6
KRNL_CHKOUT = $FFC9
KRNL_CHRIN = $FFCF
KRNL_CHROUT = $FFD2
KRNL_CLALL = $FFE7
KRNL_CLOSE = $FFC3
KRNL_CLRCHN = $FFCC
KRNL_GETIN = $FFE4
KRNL_IECIN = $FFA5
KRNL_IECOUT = $FFA8
KRNL_IOBASE = $FFF3
KRNL_IOINIT = $FF84
KRNL_LISTEN = $FFB1
KRNL_LOAD = $FFD5
KRNL_LSTNSA = $FF93
KRNL_MEMBOT = $FF99
KRNL_MEMTOP = $FF9C
KRNL_OPEN = $FFC0
KRNL_PLOT = $FFF0
KRNL_RAMTAS = $FF87
KRNL_RDTIM = $FFDE
KRNL_READST = $FFB7
KRNL_RESTOR = $FF8A
KRNL_SAVE = $FFD8
KRNL_SCNKEY = $FF9F
KRNL_SCREEN = $FFED
KRNL_SETLFS = $FFBA
KRNL_SETMSG = $FF90
KRNL_SETNAM = $FFBD
KRNL_SETTIM = $FFDB
KRNL_SETTMO = $FFA2
KRNL_STOP = $FFE1
KRNL_TALK = $FFB4
KRNL_TALKSA = $FF96
KRNL_UDTIM = $FFEA
KRNL_UNLSTN = $FFAE
KRNL_UNTALK = $FFAB
KRNL_VECTOR = $FF8D