
; Generated by CharPad 2. Assemble with 64TASS or similar.


; General constants:-

TRUE = 1
FALSE = 0
COLRMETH_GLOBAL = 0
COLRMETH_PERTILE = 1
COLRMETH_PERCHAR = 2


; Project constants:-

COLOURING_METHOD = COLRMETH_PERCHAR
CHAR_MULTICOLOUR_MODE = TRUE
COLR_SCREEN = 0
COLR_CHAR_DEF = 11
COLR_CHAR_MC1 = 14
COLR_CHAR_MC2 = 6
CHAR_COUNT = 73
TILE_COUNT = 18
TILE_WID = 4
TILE_HEI = 4
MAP_WID = 10
MAP_HEI = 5
MAP_WID_CHRS = 40
MAP_HEI_CHRS = 20
MAP_WID_PXLS = 320
MAP_HEI_PXLS = 160


; Data block size constants:-

SZ_CHARSET_DATA        = 584
SZ_CHARSET_ATTRIB_DATA = 73
SZ_TILESET_DATA        = 288
SZ_MAP_DATA            = 50


; Data block address constants (dummy values):-

ADDR_CHARSET_DATA        = $1000   ; nb. label = 'charset_data'        (block size = $248).
ADDR_CHARSET_ATTRIB_DATA = $2000   ; nb. label = 'charset_attrib_data' (block size = $49).
ADDR_TILESET_DATA        = $3000   ; nb. label = 'tileset_data'        (block size = $120).
ADDR_MAP_DATA            = $5000   ; nb. label = 'map_data'            (block size = $32).



; * INSERT EXAMPLE PROGRAM HERE! * (Or just include this file in your project).



; CHAR SET DATA : 73 (8 byte) chars : total size is 584 ($248) bytes.

* = ADDR_CHARSET_DATA
charset_data

.byte $aa,$95,$90,$90,$90,$90,$90,$90,$aa,$55,$00,$00,$00,$00,$00,$00
.byte $90,$90,$90,$90,$90,$90,$90,$90,$00,$00,$00,$0c,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00,$aa,$55,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$0c,$3f,$0c,$00,$00,$00,$00,$00,$0c,$3f,$0c,$00,$00
.byte $aa,$56,$06,$06,$06,$06,$06,$06,$06,$06,$06,$06,$06,$06,$06,$06
.byte $aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$ab,$ad,$b5,$d5
.byte $ab,$ad,$b5,$d5,$55,$55,$55,$55,$ff,$55,$55,$55,$55,$55,$55,$55
.byte $ff,$d5,$d5,$d5,$d5,$d5,$d5,$ff,$ff,$55,$55,$55,$55,$55,$55,$ff
.byte $00,$00,$00,$0c,$00,$00,$00,$00,$90,$90,$90,$90,$90,$90,$95,$aa
.byte $00,$00,$00,$00,$00,$00,$55,$aa,$00,$03,$0f,$0f,$3f,$3f,$ff,$ff
.byte $03,$03,$0f,$0f,$0f,$3f,$55,$aa,$ff,$f0,$f3,$f0,$ff,$ff,$55,$aa
.byte $00,$00,$00,$00,$00,$00,$00,$0f,$06,$06,$06,$06,$06,$06,$06,$f6
.byte $00,$00,$00,$00,$03,$0f,$30,$cf,$00,$03,$3c,$ff,$3f,$ff,$f3,$f3
.byte $3f,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$f6,$f6,$f6,$36,$c6,$c6,$f6,$f6
.byte $33,$cf,$cc,$c3,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff,$ff
.byte $ff,$cf,$c3,$f3,$c3,$cf,$ff,$ff,$f6,$f6,$f6,$f6,$f6,$f6,$f6,$f6
.byte $fc,$c0,$3f,$ff,$ff,$ff,$55,$aa,$3f,$ff,$ff,$ff,$ff,$ff,$55,$aa
.byte $ff,$ff,$ff,$cf,$ff,$ff,$55,$aa,$f6,$f6,$f6,$f6,$f6,$f6,$56,$aa
.byte $ea,$7a,$5e,$57,$55,$55,$55,$55,$aa,$aa,$aa,$aa,$ea,$7a,$5e,$57
.byte $ff,$57,$57,$57,$57,$57,$57,$ff,$aa,$aa,$a2,$aa,$9a,$9a,$aa,$aa
.byte $a8,$a3,$8f,$3f,$3f,$3f,$3f,$3f,$3f,$3f,$3d,$35,$16,$1a,$1b,$1a
.byte $fc,$fc,$7c,$5c,$94,$a4,$a4,$a4,$2a,$ca,$f2,$fc,$fc,$fc,$fc,$fc
.byte $3f,$3f,$3f,$3f,$3f,$3f,$3f,$3f,$1a,$1a,$16,$35,$3d,$3f,$3d,$3b
.byte $e4,$a4,$94,$5c,$7c,$fc,$7c,$ec,$fc,$fc,$fc,$fc,$fc,$fc,$fc,$fc
.byte $3f,$3f,$3f,$3f,$33,$44,$55,$55,$3d,$3f,$3f,$3f,$0f,$53,$54,$55
.byte $7c,$fc,$fc,$fc,$f0,$c5,$15,$55,$fc,$fc,$fc,$fc,$cc,$11,$55,$55
.byte $ff,$55,$51,$44,$51,$54,$55,$ff,$ff,$55,$11,$44,$11,$44,$55,$ff
.byte $ff,$55,$11,$44,$11,$45,$55,$ff,$a8,$a3,$a3,$a3,$a3,$a1,$a1,$85
.byte $2a,$ca,$ca,$ca,$ca,$8a,$8a,$a2,$85,$86,$86,$86,$8a,$86,$88,$82
.byte $a2,$a2,$a2,$a2,$a2,$a2,$22,$82,$3a,$3a,$3a,$3a,$3e,$3f,$3f,$3f
.byte $82,$ac,$ac,$bc,$bc,$fc,$fc,$fc,$aa,$aa,$aa,$aa,$aa,$aa,$aa,$aa
.byte $ff,$55,$55,$55,$55,$55,$55,$57,$ff,$55,$55,$57,$5d,$75,$d5,$55
.byte $fe,$7e,$de,$5e,$5e,$5e,$5e,$5e,$55,$55,$55,$55,$57,$5e,$7a,$ea
.byte $5e,$5e,$7a,$ea,$aa,$aa,$aa,$aa,$bf,$bd,$b7,$b5,$b5,$b5,$b5,$b5
.byte $ff,$55,$55,$d5,$75,$5d,$57,$55,$ff,$55,$55,$55,$55,$55,$55,$d5
.byte $b5,$b5,$ad,$ab,$aa,$aa,$aa,$aa,$55,$55,$55,$55,$d5,$b5,$ad,$ab
.byte $55,$55,$55,$99,$66,$99,$66,$99



; CHAR SET ATTRIBUTE DATA : 73 attributes : total size is 73 ($49) bytes.
; nb. Upper nybbles = Material, Lower nybbles = Colour.

* = ADDR_CHARSET_ATTRIB_DATA
charset_attrib_data

.byte $0b,$08,$08,$09,$00,$09,$08,$09,$08,$08,$19,$0b,$0b,$0b,$fb,$fb
.byte $08,$08,$08,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d,$0d
.byte $0d,$0d,$0d,$0d,$0b,$0b,$fb,$1b,$09,$09,$09,$09,$09,$09,$09,$09
.byte $09,$09,$09,$09,$fb,$fb,$fb,$09,$09,$09,$09,$09,$09,$09,$0b,$0b
.byte $0b,$1b,$1b,$0b,$0b,$0b,$1b,$1b,$f9



; TILE SET DATA : 18 (4x4) tiles : total size is 288 ($120) bytes.

* = ADDR_TILESET_DATA
tileset_data

.byte $00,$01,$01,$01,$02,$03,$04,$04,$02,$04,$04,$03,$02,$04,$04,$04
.byte $01,$01,$01,$05,$06,$03,$04,$04,$04,$04,$04,$04,$07,$04,$04,$03
.byte $01,$01,$01,$01,$04,$04,$04,$07,$04,$03,$04,$04,$04,$04,$04,$04
.byte $01,$01,$01,$08,$04,$04,$03,$09,$03,$04,$04,$09,$04,$04,$03,$09
.byte $27,$27,$27,$27,$27,$27,$27,$27,$0b,$0c,$0d,$0d,$0e,$0f,$0f,$0f
.byte $27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27
.byte $02,$04,$03,$04,$02,$04,$04,$10,$02,$03,$04,$04,$11,$12,$12,$12
.byte $04,$04,$04,$04,$04,$04,$03,$04,$04,$03,$04,$04,$12,$12,$12,$12
.byte $04,$07,$04,$03,$04,$04,$04,$04,$10,$04,$04,$13,$12,$12,$14,$15
.byte $04,$04,$16,$17,$18,$19,$1a,$1b,$1c,$1d,$1e,$1f,$20,$21,$22,$23
.byte $27,$27,$27,$27,$27,$27,$27,$27,$0d,$0d,$24,$25,$0f,$0f,$0f,$26
.byte $27,$27,$27,$27,$27,$27,$27,$27,$0d,$0d,$0d,$0d,$0f,$0f,$0f,$0f
.byte $28,$29,$2a,$2b,$2c,$2d,$2e,$2f,$30,$31,$32,$33,$34,$35,$35,$36
.byte $27,$27,$27,$27,$27,$37,$38,$27,$27,$39,$3a,$27,$27,$3b,$3c,$27
.byte $27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$0b,$0c,$27,$27,$0e,$0f
.byte $27,$27,$27,$27,$27,$27,$27,$27,$0d,$3e,$3f,$40,$0f,$26,$41,$42
.byte $27,$27,$27,$27,$27,$27,$27,$27,$43,$44,$45,$0d,$46,$47,$0e,$0f
.byte $48,$48,$48,$48,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27



; MAP DATA : 1 (10x5) map : total size is 50 ($32) bytes.

* = ADDR_MAP_DATA
map_data

.byte $11,$11,$11,$11,$11,$11,$11,$11,$11,$11,$05,$05,$00,$01,$02,$01
.byte $02,$03,$05,$05,$05,$05,$06,$07,$07,$07,$08,$09,$05,$05,$05,$05
.byte $05,$05,$05,$05,$05,$05,$0d,$05,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b
.byte $0c,$0a


